config/routes.rb
Rails.application.routes.draw do
  resources :mycontacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mycontacts_controller.rb
class MycontactsController < ApplicationController
  before_action :set_mycontact, only: %i[ show edit update destroy ]

  # GET /mycontacts or /mycontacts.json
  def index
    @mycontacts = Mycontact.all
  end

  # GET /mycontacts/1 or /mycontacts/1.json
  def show
  end

  # GET /mycontacts/new
  def new
    @mycontact = Mycontact.new
  end

  # GET /mycontacts/1/edit
  def edit
  end

  # POST /mycontacts or /mycontacts.json
  def create
    @mycontact = Mycontact.new(mycontact_params)

    respond_to do |format|
      if @mycontact.save
        format.html { redirect_to mycontact_url(@mycontact), notice: "Mycontact was successfully created." }
        format.json { render :show, status: :created, location: @mycontact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mycontacts/1 or /mycontacts/1.json
  def update
    respond_to do |format|
      if @mycontact.update(mycontact_params)
        format.html { redirect_to mycontact_url(@mycontact), notice: "Mycontact was successfully updated." }
        format.json { render :show, status: :ok, location: @mycontact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycontacts/1 or /mycontacts/1.json
  def destroy
    @mycontact.destroy

    respond_to do |format|
      format.html { redirect_to mycontacts_url, notice: "Mycontact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycontact
      @mycontact = Mycontact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mycontact_params
      params.require(:mycontact).permit(:name, :age, :nationality, :mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mycontacts_helper.rb
module MycontactsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaffoldSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mycontacts/_form.html.erb
<%= form_with(model: mycontact) do |form| %>
  <% if mycontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mycontact.errors.count, "error") %> prohibited this mycontact from being saved:</h2>

      <ul>
        <% mycontact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.check_box :nationality %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_area :mail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mycontacts/edit.html.erb
<h1>Editing Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Show', @mycontact %> |
<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mycontacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mycontacts.each do |mycontact| %>
      <tr>
        <td><%= mycontact.name %></td>
        <td><%= mycontact.age %></td>
        <td><%= mycontact.nationality %></td>
        <td><%= mycontact.mail %></td>
        <td><%= link_to 'Show', mycontact %></td>
        <td><%= link_to 'Edit', edit_mycontact_path(mycontact) %></td>
        <td><%= link_to 'Destroy', mycontact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mycontact', new_mycontact_path %>

app/views/mycontacts/new.html.erb
<h1>New Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mycontact.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @mycontact.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @mycontact.nationality %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mycontact.mail %>
</p>

<%= link_to 'Edit', edit_mycontact_path(@mycontact) %> |
<%= link_to 'Back', mycontacts_path %>